### ISSUE TITLE
Add to Addon Manager

### ISSUE THREAD

**Issue by luzpaz** [turn211/ProDarkThemePreferencePack#1]
cc @chennes
Hey! I'm traveling atm and can't attend to this, would you mind making this available pre v0.20 release? 

Edit: https://forum.freecad.org/viewtopic.php?f=34&t=68771

**Comment by turn211** [comment]
All ready for Addons
https://forum.freecadweb.org/viewtopic.php?f=34&t=68817

**Comment by chennes** [comment]
Are you going to submit a PR to https://github.com/FreeCAD/FreeCAD-addons (you just need to add your repo to the .gitmodules file)?

ETA: Nevermind, I just went ahead with it (I assume based on your announcement that this is OK...if not please let me know)

**Comment by luzpaz** [comment]
Closed with https://github.com/FreeCAD/FreeCAD-addons/commit/4d803504fa9181063f104baa8c50139d86e15e7f

Edit: thanks chennes!
